<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-18T01:16:34 IST" name="Default suite" finished-at="2021-08-18T01:16:34 IST" duration-ms="46">
    <groups>
    </groups>
    <test started-at="2021-08-18T01:16:34 IST" name="Default test" finished-at="2021-08-18T01:16:34 IST" duration-ms="46">
      <class name="TestCalculate">
        <test-method is-config="true" signature="init()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="init" finished-at="2021-08-18T01:16:34 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="NumbersCommaDelimitedReturnSum()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="NumbersCommaDelimitedReturnSum" finished-at="2021-08-18T01:16:34 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NumbersCommaDelimitedReturnSum -->
        <test-method signature="NumbersNewLineDelimitedReturnSum()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="NumbersNewLineDelimitedReturnSum" finished-at="2021-08-18T01:16:34 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NumbersNewLineDelimitedReturnSum -->
        <test-method signature="emptyStringReturnsZero()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="emptyStringReturnsZero" finished-at="2021-08-18T01:16:34 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyStringReturnsZero -->
        <test-method signature="negativeValueReturnsException()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="negativeValueReturnsException" finished-at="2021-08-18T01:16:34 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestCalculate.negativeValueReturnsException()[pri:0, instance:TestCalculate@4313f5bc] should have thrown an exception of type class java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestCalculate.negativeValueReturnsException()[pri:0, instance:TestCalculate@4313f5bc] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeValueReturnsException -->
        <test-method signature="singleNumberReturnsValue()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="singleNumberReturnsValue" finished-at="2021-08-18T01:16:34 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleNumberReturnsValue -->
        <test-method signature="twoNumbersCommaDelimitedReturnSum()[pri:0, instance:TestCalculate@4313f5bc]" started-at="2021-08-18T01:16:34 IST" name="twoNumbersCommaDelimitedReturnSum" finished-at="2021-08-18T01:16:34 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoNumbersCommaDelimitedReturnSum -->
      </class> <!-- TestCalculate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
